version: "3.9"

services:
  task-manager-api:
    build: ./api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
  postgres:
    image: postgres:16-alpine
    ports:
      - 4001:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - ./api/.env
    networks:
      - postgres-db-network
  task-manager:
    build: ./client
    ports:
      - "3000:3000"  
    stdin_open: true
    tty: true 
volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
networks:
  postgres-db-network:
    driver: bridge
