version: "3.9"

services:
  task-manager:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./vol:/app/vol
    env_file:
      - .env
  postgres:
    image: postgres:16-alpine
    ports:
      - 4001:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - postgres-db-network
volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
networks:
  postgres-db-network:
    driver: bridge
