version: '3.9'

services:
  task-manager:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /code
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=taskmanagerdb